export interface Country {
    id: number;
    country: string;
    callingCode: string;
    countryCode: string;
    currencyCode: string | null;
    currencyName: string | null;
    curencySymbol: string | null;
    flag: string | null;
    isActive: boolean;
}

export const countriesData: Country[] = [
        {
            "id": 253,
            "country": "",
            "callingCode": "+0",
            "countryCode": "",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 1,
            "country": "Afghanistan",
            "callingCode": "93",
            "countryCode": "AFG",
            "currencyCode": "AFN",
            "currencyName": "Afghan afghani",
            "curencySymbol": "؋",
            "flag": "54.89.97.147:3002/static/data/afg.svg",
            "isActive": true
        },
        {
            "id": 3,
            "country": "Albania",
            "callingCode": "355",
            "countryCode": "ALB",
            "currencyCode": "ALL",
            "currencyName": "Albanian lek",
            "curencySymbol": "L",
            "flag": "54.89.97.147:3002/static/data/alb.svg",
            "isActive": true
        },
        {
            "id": 4,
            "country": "Algeria",
            "callingCode": "213",
            "countryCode": "DZA",
            "currencyCode": "DZD",
            "currencyName": "Algerian dinar",
            "curencySymbol": "د.ج",
            "flag": "54.89.97.147:3002/static/data/dza.svg",
            "isActive": true
        },
        {
            "id": 5,
            "country": "American Samoa",
            "callingCode": "1684",
            "countryCode": "ASM",
            "currencyCode": "USD",
            "currencyName": "United State Dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/asm.svg",
            "isActive": true
        },
        {
            "id": 6,
            "country": "Andorra",
            "callingCode": "376",
            "countryCode": "AND",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/and.svg",
            "isActive": true
        },
        {
            "id": 7,
            "country": "Angola",
            "callingCode": "244",
            "countryCode": "AGO",
            "currencyCode": "AOA",
            "currencyName": "Angolan kwanza",
            "curencySymbol": "Kz",
            "flag": "54.89.97.147:3002/static/data/ago.svg",
            "isActive": true
        },
        {
            "id": 8,
            "country": "Anguilla",
            "callingCode": "1264",
            "countryCode": "AIA",
            "currencyCode": "XCD",
            "currencyName": "East Caribbean dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/aia.svg",
            "isActive": true
        },
        {
            "id": 9,
            "country": "Antarctica",
            "callingCode": "672",
            "countryCode": "ATA",
            "currencyCode": "AUD",
            "currencyName": "Australian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/ata.svg",
            "isActive": true
        },
        {
            "id": 10,
            "country": "Antigua and Barbuda",
            "callingCode": "1268",
            "countryCode": "ATG",
            "currencyCode": "XCD",
            "currencyName": "East Caribbean dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/atg.svg",
            "isActive": true
        },
        {
            "id": 11,
            "country": "Argentina",
            "callingCode": "54",
            "countryCode": "ARG",
            "currencyCode": "ARS",
            "currencyName": "Argentine peso",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/arg.svg",
            "isActive": true
        },
        {
            "id": 12,
            "country": "Armenia",
            "callingCode": "374",
            "countryCode": "ARM",
            "currencyCode": "AMD",
            "currencyName": "Armenian dram",
            "curencySymbol": null,
            "flag": "54.89.97.147:3002/static/data/arm.svg",
            "isActive": true
        },
        {
            "id": 13,
            "country": "Aruba",
            "callingCode": "297",
            "countryCode": "ABW",
            "currencyCode": "AWG",
            "currencyName": "Aruban florin",
            "curencySymbol": "ƒ",
            "flag": "54.89.97.147:3002/static/data/abw.svg",
            "isActive": true
        },
        {
            "id": 251,
            "country": "Ascension Island",
            "callingCode": "247",
            "countryCode": "Ascension Island",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 14,
            "country": "Australia",
            "callingCode": "61",
            "countryCode": "AUS",
            "currencyCode": "AUD",
            "currencyName": "Australian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/aus.svg",
            "isActive": true
        },
        {
            "id": 15,
            "country": "Austria",
            "callingCode": "43",
            "countryCode": "AUT",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/aut.svg",
            "isActive": true
        },
        {
            "id": 16,
            "country": "Azerbaijan",
            "callingCode": "994",
            "countryCode": "AZE",
            "currencyCode": "AZN",
            "currencyName": "Azerbaijani manat",
            "curencySymbol": null,
            "flag": "54.89.97.147:3002/static/data/aze.svg",
            "isActive": true
        },
        {
            "id": 17,
            "country": "Bahamas",
            "callingCode": "1242",
            "countryCode": "BHS",
            "currencyCode": "BSD",
            "currencyName": "Bahamian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/bhs.svg",
            "isActive": true
        },
        {
            "id": 18,
            "country": "Bahrain",
            "callingCode": "973",
            "countryCode": "BHR",
            "currencyCode": "BHD",
            "currencyName": "Bahraini dinar",
            "curencySymbol": ".د.ب",
            "flag": "54.89.97.147:3002/static/data/bhr.svg",
            "isActive": true
        },
        {
            "id": 19,
            "country": "Bangladesh",
            "callingCode": "880",
            "countryCode": "BGD",
            "currencyCode": "BDT",
            "currencyName": "Bangladeshi taka",
            "curencySymbol": "৳",
            "flag": "54.89.97.147:3002/static/data/bgd.svg",
            "isActive": true
        },
        {
            "id": 20,
            "country": "Barbados",
            "callingCode": "1246",
            "countryCode": "BRB",
            "currencyCode": "BBD",
            "currencyName": "Barbadian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/brb.svg",
            "isActive": true
        },
        {
            "id": 21,
            "country": "Belarus",
            "callingCode": "375",
            "countryCode": "BLR",
            "currencyCode": "BYN",
            "currencyName": "New Belarusian ruble",
            "curencySymbol": "Br",
            "flag": "54.89.97.147:3002/static/data/blr.svg",
            "isActive": true
        },
        {
            "id": 22,
            "country": "Belgium",
            "callingCode": "32",
            "countryCode": "BEL",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/bel.svg",
            "isActive": true
        },
        {
            "id": 23,
            "country": "Belize",
            "callingCode": "501",
            "countryCode": "BLZ",
            "currencyCode": "BZD",
            "currencyName": "Belize dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/blz.svg",
            "isActive": true
        },
        {
            "id": 24,
            "country": "Benin",
            "callingCode": "229",
            "countryCode": "BEN",
            "currencyCode": "XOF",
            "currencyName": "West African CFA franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/ben.svg",
            "isActive": true
        },
        {
            "id": 25,
            "country": "Bermuda",
            "callingCode": "1441",
            "countryCode": "BMU",
            "currencyCode": "BMD",
            "currencyName": "Bermudian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/bmu.svg",
            "isActive": true
        },
        {
            "id": 26,
            "country": "Bhutan",
            "callingCode": "975",
            "countryCode": "BTN",
            "currencyCode": "BTN",
            "currencyName": "Bhutanese ngultrum",
            "curencySymbol": "Nu.",
            "flag": "54.89.97.147:3002/static/data/btn.svg",
            "isActive": true
        },
        {
            "id": 27,
            "country": "Bolivia (Plurinational State of)",
            "callingCode": "591",
            "countryCode": "BOL",
            "currencyCode": "BOB",
            "currencyName": "Bolivian boliviano",
            "curencySymbol": "Bs.",
            "flag": "54.89.97.147:3002/static/data/bol.svg",
            "isActive": true
        },
        {
            "id": 28,
            "country": "Bonaire, Sint Eustatius and Saba",
            "callingCode": "5997",
            "countryCode": "BES",
            "currencyCode": "USD",
            "currencyName": "United States dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/bes.svg",
            "isActive": true
        },
        {
            "id": 29,
            "country": "Bosnia and Herzegovina",
            "callingCode": "387",
            "countryCode": "BIH",
            "currencyCode": "BAM",
            "currencyName": "Bosnia and Herzegovina convertible mark",
            "curencySymbol": null,
            "flag": "54.89.97.147:3002/static/data/bih.svg",
            "isActive": true
        },
        {
            "id": 30,
            "country": "Botswana",
            "callingCode": "267",
            "countryCode": "BWA",
            "currencyCode": "BWP",
            "currencyName": "Botswana pula",
            "curencySymbol": "P",
            "flag": "54.89.97.147:3002/static/data/bwa.svg",
            "isActive": true
        },
        {
            "id": 31,
            "country": "Bouvet Island",
            "callingCode": "",
            "countryCode": "BVT",
            "currencyCode": "NOK",
            "currencyName": "Norwegian krone",
            "curencySymbol": "kr",
            "flag": "54.89.97.147:3002/static/data/bvt.svg",
            "isActive": true
        },
        {
            "id": 32,
            "country": "Brazil",
            "callingCode": "55",
            "countryCode": "BRA",
            "currencyCode": "BRL",
            "currencyName": "Brazilian real",
            "curencySymbol": "R$",
            "flag": "54.89.97.147:3002/static/data/bra.svg",
            "isActive": true
        },
        {
            "id": 33,
            "country": "British Indian Ocean Territory",
            "callingCode": "246",
            "countryCode": "IOT",
            "currencyCode": "USD",
            "currencyName": "United States dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/iot.svg",
            "isActive": true
        },
        {
            "id": 252,
            "country": "Brunei\nDarussalam",
            "callingCode": "673",
            "countryCode": "Brunei\nDarussalam",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 37,
            "country": "Brunei Darussalam",
            "callingCode": "673",
            "countryCode": "BRN",
            "currencyCode": "BND",
            "currencyName": "Brunei dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/brn.svg",
            "isActive": true
        },
        {
            "id": 38,
            "country": "Bulgaria",
            "callingCode": "359",
            "countryCode": "BGR",
            "currencyCode": "BGN",
            "currencyName": "Bulgarian lev",
            "curencySymbol": "лв",
            "flag": "54.89.97.147:3002/static/data/bgr.svg",
            "isActive": true
        },
        {
            "id": 39,
            "country": "Burkina Faso",
            "callingCode": "226",
            "countryCode": "BFA",
            "currencyCode": "XOF",
            "currencyName": "West African CFA franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/bfa.svg",
            "isActive": true
        },
        {
            "id": 40,
            "country": "Burundi",
            "callingCode": "257",
            "countryCode": "BDI",
            "currencyCode": "BIF",
            "currencyName": "Burundian franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/bdi.svg",
            "isActive": true
        },
        {
            "id": 44,
            "country": "Cabo Verde",
            "callingCode": "238",
            "countryCode": "CPV",
            "currencyCode": "CVE",
            "currencyName": "Cape Verdean escudo",
            "curencySymbol": "Esc",
            "flag": "54.89.97.147:3002/static/data/cpv.svg",
            "isActive": true
        },
        {
            "id": 41,
            "country": "Cambodia",
            "callingCode": "855",
            "countryCode": "KHM",
            "currencyCode": "KHR",
            "currencyName": "Cambodian riel",
            "curencySymbol": "៛",
            "flag": "54.89.97.147:3002/static/data/khm.svg",
            "isActive": true
        },
        {
            "id": 42,
            "country": "Cameroon",
            "callingCode": "237",
            "countryCode": "CMR",
            "currencyCode": "XAF",
            "currencyName": "Central African CFA franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/cmr.svg",
            "isActive": true
        },
        {
            "id": 43,
            "country": "Canada",
            "callingCode": "1",
            "countryCode": "CAN",
            "currencyCode": "CAD",
            "currencyName": "Canadian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/can.svg",
            "isActive": true
        },
        {
            "id": 254,
            "country": "Canary Islands",
            "callingCode": "34",
            "countryCode": "Canary Islands",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 255,
            "country": "Cape Verde",
            "callingCode": "238",
            "countryCode": "Cape Verde",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 45,
            "country": "Cayman Islands",
            "callingCode": "1345",
            "countryCode": "CYM",
            "currencyCode": "KYD",
            "currencyName": "Cayman Islands dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/cym.svg",
            "isActive": true
        },
        {
            "id": 46,
            "country": "Central African Republic",
            "callingCode": "236",
            "countryCode": "CAF",
            "currencyCode": "XAF",
            "currencyName": "Central African CFA franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/caf.svg",
            "isActive": true
        },
        {
            "id": 47,
            "country": "Chad",
            "callingCode": "235",
            "countryCode": "TCD",
            "currencyCode": "XAF",
            "currencyName": "Central African CFA franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/tcd.svg",
            "isActive": true
        },
        {
            "id": 48,
            "country": "Chile",
            "callingCode": "56",
            "countryCode": "CHL",
            "currencyCode": "CLP",
            "currencyName": "Chilean peso",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/chl.svg",
            "isActive": true
        },
        {
            "id": 49,
            "country": "China",
            "callingCode": "86",
            "countryCode": "CHN",
            "currencyCode": "CNY",
            "currencyName": "Chinese yuan",
            "curencySymbol": "¥",
            "flag": "54.89.97.147:3002/static/data/chn.svg",
            "isActive": true
        },
        {
            "id": 50,
            "country": "Christmas Island",
            "callingCode": "61",
            "countryCode": "CXR",
            "currencyCode": "AUD",
            "currencyName": "Australian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/cxr.svg",
            "isActive": true
        },
        {
            "id": 51,
            "country": "Cocos (Keeling) Islands",
            "callingCode": "61",
            "countryCode": "CCK",
            "currencyCode": "AUD",
            "currencyName": "Australian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/cck.svg",
            "isActive": true
        },
        {
            "id": 52,
            "country": "Colombia",
            "callingCode": "57",
            "countryCode": "COL",
            "currencyCode": "COP",
            "currencyName": "Colombian peso",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/col.svg",
            "isActive": true
        },
        {
            "id": 53,
            "country": "Comoros",
            "callingCode": "269",
            "countryCode": "COM",
            "currencyCode": "KMF",
            "currencyName": "Comorian franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/com.svg",
            "isActive": true
        },
        {
            "id": 54,
            "country": "Congo",
            "callingCode": "242",
            "countryCode": "COG",
            "currencyCode": "XAF",
            "currencyName": "Central African CFA franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/cog.svg",
            "isActive": true
        },
        {
            "id": 55,
            "country": "Congo (Democratic Republic of the)",
            "callingCode": "243",
            "countryCode": "COD",
            "currencyCode": "CDF",
            "currencyName": "Congolese franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/cod.svg",
            "isActive": true
        },
        {
            "id": 256,
            "country": "Congo, Dem.\nRepublic of",
            "callingCode": "243",
            "countryCode": "Congo, Dem.\nRepublic of",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 56,
            "country": "Cook Islands",
            "callingCode": "682",
            "countryCode": "COK",
            "currencyCode": "NZD",
            "currencyName": "New Zealand dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/cok.svg",
            "isActive": true
        },
        {
            "id": 57,
            "country": "Costa Rica",
            "callingCode": "506",
            "countryCode": "CRI",
            "currencyCode": "CRC",
            "currencyName": "Costa Rican colón",
            "curencySymbol": "₡",
            "flag": "54.89.97.147:3002/static/data/cri.svg",
            "isActive": true
        },
        {
            "id": 58,
            "country": "Croatia",
            "callingCode": "385",
            "countryCode": "HRV",
            "currencyCode": "HRK",
            "currencyName": "Croatian kuna",
            "curencySymbol": "kn",
            "flag": "54.89.97.147:3002/static/data/hrv.svg",
            "isActive": true
        },
        {
            "id": 59,
            "country": "Cuba",
            "callingCode": "53",
            "countryCode": "CUB",
            "currencyCode": "CUC",
            "currencyName": "Cuban convertible peso",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/cub.svg",
            "isActive": true
        },
        {
            "id": 60,
            "country": "Curaçao",
            "callingCode": "599",
            "countryCode": "CUW",
            "currencyCode": "ANG",
            "currencyName": "Netherlands Antillean guilder",
            "curencySymbol": "ƒ",
            "flag": "54.89.97.147:3002/static/data/cuw.svg",
            "isActive": true
        },
        {
            "id": 61,
            "country": "Cyprus",
            "callingCode": "357",
            "countryCode": "CYP",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/cyp.svg",
            "isActive": true
        },
        {
            "id": 62,
            "country": "Czech Republic",
            "callingCode": "420",
            "countryCode": "CZE",
            "currencyCode": "CZK",
            "currencyName": "Czech koruna",
            "curencySymbol": "Kč",
            "flag": "54.89.97.147:3002/static/data/cze.svg",
            "isActive": true
        },
        {
            "id": 107,
            "country": "Côte d'Ivoire",
            "callingCode": "225",
            "countryCode": "CIV",
            "currencyCode": "XOF",
            "currencyName": "West African CFA franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/civ.svg",
            "isActive": true
        },
        {
            "id": 63,
            "country": "Denmark",
            "callingCode": "45",
            "countryCode": "DNK",
            "currencyCode": "DKK",
            "currencyName": "Danish krone",
            "curencySymbol": "kr",
            "flag": "54.89.97.147:3002/static/data/dnk.svg",
            "isActive": true
        },
        {
            "id": 64,
            "country": "Djibouti",
            "callingCode": "253",
            "countryCode": "DJI",
            "currencyCode": "DJF",
            "currencyName": "Djiboutian franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/dji.svg",
            "isActive": true
        },
        {
            "id": 65,
            "country": "Dominica",
            "callingCode": "1767",
            "countryCode": "DMA",
            "currencyCode": "XCD",
            "currencyName": "East Caribbean dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/dma.svg",
            "isActive": true
        },
        {
            "id": 257,
            "country": "Dominican\nRepublic",
            "callingCode": "1",
            "countryCode": "Dominican\nRepublic",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 66,
            "country": "Dominican Republic",
            "callingCode": "1809",
            "countryCode": "DOM",
            "currencyCode": "DOP",
            "currencyName": "Dominican peso",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/dom.svg",
            "isActive": true
        },
        {
            "id": 67,
            "country": "Ecuador",
            "callingCode": "593",
            "countryCode": "ECU",
            "currencyCode": "USD",
            "currencyName": "United States dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/ecu.svg",
            "isActive": true
        },
        {
            "id": 68,
            "country": "Egypt",
            "callingCode": "20",
            "countryCode": "EGY",
            "currencyCode": "EGP",
            "currencyName": "Egyptian pound",
            "curencySymbol": "£",
            "flag": "54.89.97.147:3002/static/data/egy.svg",
            "isActive": true
        },
        {
            "id": 69,
            "country": "El Salvador",
            "callingCode": "503",
            "countryCode": "SLV",
            "currencyCode": "USD",
            "currencyName": "United States dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/slv.svg",
            "isActive": true
        },
        {
            "id": 70,
            "country": "Equatorial Guinea",
            "callingCode": "240",
            "countryCode": "GNQ",
            "currencyCode": "XAF",
            "currencyName": "Central African CFA franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/gnq.svg",
            "isActive": true
        },
        {
            "id": 71,
            "country": "Eritrea",
            "callingCode": "291",
            "countryCode": "ERI",
            "currencyCode": "ERN",
            "currencyName": "Eritrean nakfa",
            "curencySymbol": "Nfk",
            "flag": "54.89.97.147:3002/static/data/eri.svg",
            "isActive": true
        },
        {
            "id": 72,
            "country": "Estonia",
            "callingCode": "372",
            "countryCode": "EST",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/est.svg",
            "isActive": true
        },
        {
            "id": 73,
            "country": "Ethiopia",
            "callingCode": "251",
            "countryCode": "ETH",
            "currencyCode": "ETB",
            "currencyName": "Ethiopian birr",
            "curencySymbol": "Br",
            "flag": "54.89.97.147:3002/static/data/eth.svg",
            "isActive": true
        },
        {
            "id": 74,
            "country": "Falkland Islands (Malvinas)",
            "callingCode": "500",
            "countryCode": "FLK",
            "currencyCode": "FKP",
            "currencyName": "Falkland Islands pound",
            "curencySymbol": "£",
            "flag": "54.89.97.147:3002/static/data/flk.svg",
            "isActive": true
        },
        {
            "id": 75,
            "country": "Faroe Islands",
            "callingCode": "298",
            "countryCode": "FRO",
            "currencyCode": "DKK",
            "currencyName": "Danish krone",
            "curencySymbol": "kr",
            "flag": "54.89.97.147:3002/static/data/fro.svg",
            "isActive": true
        },
        {
            "id": 76,
            "country": "Fiji",
            "callingCode": "679",
            "countryCode": "FJI",
            "currencyCode": "FJD",
            "currencyName": "Fijian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/fji.svg",
            "isActive": true
        },
        {
            "id": 77,
            "country": "Finland",
            "callingCode": "358",
            "countryCode": "FIN",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/fin.svg",
            "isActive": true
        },
        {
            "id": 78,
            "country": "France",
            "callingCode": "33",
            "countryCode": "FRA",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/fra.svg",
            "isActive": true
        },
        {
            "id": 79,
            "country": "French Guiana",
            "callingCode": "594",
            "countryCode": "GUF",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/guf.svg",
            "isActive": true
        },
        {
            "id": 80,
            "country": "French Polynesia",
            "callingCode": "689",
            "countryCode": "PYF",
            "currencyCode": "XPF",
            "currencyName": "CFP franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/pyf.svg",
            "isActive": true
        },
        {
            "id": 81,
            "country": "French Southern Territories",
            "callingCode": "",
            "countryCode": "ATF",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/atf.svg",
            "isActive": true
        },
        {
            "id": 82,
            "country": "Gabon",
            "callingCode": "241",
            "countryCode": "GAB",
            "currencyCode": "XAF",
            "currencyName": "Central African CFA franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/gab.svg",
            "isActive": true
        },
        {
            "id": 83,
            "country": "Gambia",
            "callingCode": "220",
            "countryCode": "GMB",
            "currencyCode": "GMD",
            "currencyName": "Gambian dalasi",
            "curencySymbol": "D",
            "flag": "54.89.97.147:3002/static/data/gmb.svg",
            "isActive": true
        },
        {
            "id": 84,
            "country": "Georgia",
            "callingCode": "995",
            "countryCode": "GEO",
            "currencyCode": "GEL",
            "currencyName": "Georgian Lari",
            "curencySymbol": "ლ",
            "flag": "54.89.97.147:3002/static/data/geo.svg",
            "isActive": true
        },
        {
            "id": 85,
            "country": "Germany",
            "callingCode": "49",
            "countryCode": "DEU",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/deu.svg",
            "isActive": true
        },
        {
            "id": 86,
            "country": "Ghana",
            "callingCode": "233",
            "countryCode": "GHA",
            "currencyCode": "GHS",
            "currencyName": "Ghanaian cedi",
            "curencySymbol": "₵",
            "flag": "54.89.97.147:3002/static/data/gha.svg",
            "isActive": true
        },
        {
            "id": 87,
            "country": "Gibraltar",
            "callingCode": "350",
            "countryCode": "GIB",
            "currencyCode": "GIP",
            "currencyName": "Gibraltar pound",
            "curencySymbol": "£",
            "flag": "54.89.97.147:3002/static/data/gib.svg",
            "isActive": true
        },
        {
            "id": 88,
            "country": "Greece",
            "callingCode": "30",
            "countryCode": "GRC",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/grc.svg",
            "isActive": true
        },
        {
            "id": 89,
            "country": "Greenland",
            "callingCode": "299",
            "countryCode": "GRL",
            "currencyCode": "DKK",
            "currencyName": "Danish krone",
            "curencySymbol": "kr",
            "flag": "54.89.97.147:3002/static/data/grl.svg",
            "isActive": true
        },
        {
            "id": 90,
            "country": "Grenada",
            "callingCode": "1473",
            "countryCode": "GRD",
            "currencyCode": "XCD",
            "currencyName": "East Caribbean dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/grd.svg",
            "isActive": true
        },
        {
            "id": 91,
            "country": "Guadeloupe",
            "callingCode": "590",
            "countryCode": "GLP",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/glp.svg",
            "isActive": true
        },
        {
            "id": 92,
            "country": "Guam",
            "callingCode": "1671",
            "countryCode": "GUM",
            "currencyCode": "USD",
            "currencyName": "United States dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/gum.svg",
            "isActive": true
        },
        {
            "id": 93,
            "country": "Guatemala",
            "callingCode": "502",
            "countryCode": "GTM",
            "currencyCode": "GTQ",
            "currencyName": "Guatemalan quetzal",
            "curencySymbol": "Q",
            "flag": "54.89.97.147:3002/static/data/gtm.svg",
            "isActive": true
        },
        {
            "id": 94,
            "country": "Guernsey",
            "callingCode": "44",
            "countryCode": "GGY",
            "currencyCode": "GBP",
            "currencyName": "British pound",
            "curencySymbol": "£",
            "flag": "54.89.97.147:3002/static/data/ggy.svg",
            "isActive": true
        },
        {
            "id": 95,
            "country": "Guinea",
            "callingCode": "224",
            "countryCode": "GIN",
            "currencyCode": "GNF",
            "currencyName": "Guinean franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/gin.svg",
            "isActive": true
        },
        {
            "id": 96,
            "country": "Guinea-Bissau",
            "callingCode": "245",
            "countryCode": "GNB",
            "currencyCode": "XOF",
            "currencyName": "West African CFA franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/gnb.svg",
            "isActive": true
        },
        {
            "id": 97,
            "country": "Guyana",
            "callingCode": "592",
            "countryCode": "GUY",
            "currencyCode": "GYD",
            "currencyName": "Guyanese dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/guy.svg",
            "isActive": true
        },
        {
            "id": 98,
            "country": "Haiti",
            "callingCode": "509",
            "countryCode": "HTI",
            "currencyCode": "HTG",
            "currencyName": "Haitian gourde",
            "curencySymbol": "G",
            "flag": "54.89.97.147:3002/static/data/hti.svg",
            "isActive": true
        },
        {
            "id": 99,
            "country": "Heard Island and McDonald Islands",
            "callingCode": "",
            "countryCode": "HMD",
            "currencyCode": "AUD",
            "currencyName": "Australian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/hmd.svg",
            "isActive": true
        },
        {
            "id": 100,
            "country": "Holy See",
            "callingCode": "379",
            "countryCode": "VAT",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/vat.svg",
            "isActive": true
        },
        {
            "id": 101,
            "country": "Honduras",
            "callingCode": "504",
            "countryCode": "HND",
            "currencyCode": "HNL",
            "currencyName": "Honduran lempira",
            "curencySymbol": "L",
            "flag": "54.89.97.147:3002/static/data/hnd.svg",
            "isActive": true
        },
        {
            "id": 102,
            "country": "Hong Kong",
            "callingCode": "852",
            "countryCode": "HKG",
            "currencyCode": "HKD",
            "currencyName": "Hong Kong dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/hkg.svg",
            "isActive": true
        },
        {
            "id": 103,
            "country": "Hungary",
            "callingCode": "36",
            "countryCode": "HUN",
            "currencyCode": "HUF",
            "currencyName": "Hungarian forint",
            "curencySymbol": "Ft",
            "flag": "54.89.97.147:3002/static/data/hun.svg",
            "isActive": true
        },
        {
            "id": 104,
            "country": "Iceland",
            "callingCode": "354",
            "countryCode": "ISL",
            "currencyCode": "ISK",
            "currencyName": "Icelandic króna",
            "curencySymbol": "kr",
            "flag": "54.89.97.147:3002/static/data/isl.svg",
            "isActive": true
        },
        {
            "id": 105,
            "country": "India",
            "callingCode": "91",
            "countryCode": "IND",
            "currencyCode": "INR",
            "currencyName": "Indian rupee",
            "curencySymbol": "₹",
            "flag": "54.89.97.147:3002/static/data/ind.svg",
            "isActive": true
        },
        {
            "id": 106,
            "country": "Indonesia",
            "callingCode": "62",
            "countryCode": "IDN",
            "currencyCode": "IDR",
            "currencyName": "Indonesian rupiah",
            "curencySymbol": "Rp",
            "flag": "54.89.97.147:3002/static/data/idn.svg",
            "isActive": true
        },
        {
            "id": 258,
            "country": "Iran",
            "callingCode": "98",
            "countryCode": "Iran",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 108,
            "country": "Iran (Islamic Republic of)",
            "callingCode": "98",
            "countryCode": "IRN",
            "currencyCode": "IRR",
            "currencyName": "Iranian rial",
            "curencySymbol": "﷼",
            "flag": "54.89.97.147:3002/static/data/irn.svg",
            "isActive": true
        },
        {
            "id": 109,
            "country": "Iraq",
            "callingCode": "964",
            "countryCode": "IRQ",
            "currencyCode": "IQD",
            "currencyName": "Iraqi dinar",
            "curencySymbol": "ع.د",
            "flag": "54.89.97.147:3002/static/data/irq.svg",
            "isActive": true
        },
        {
            "id": 110,
            "country": "Ireland",
            "callingCode": "353",
            "countryCode": "IRL",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/irl.svg",
            "isActive": true
        },
        {
            "id": 111,
            "country": "Isle of Man",
            "callingCode": "44",
            "countryCode": "IMN",
            "currencyCode": "GBP",
            "currencyName": "British pound",
            "curencySymbol": "£",
            "flag": "54.89.97.147:3002/static/data/imn.svg",
            "isActive": true
        },
        {
            "id": 112,
            "country": "Israel",
            "callingCode": "972",
            "countryCode": "ISR",
            "currencyCode": "ILS",
            "currencyName": "Israeli new shekel",
            "curencySymbol": "₪",
            "flag": "54.89.97.147:3002/static/data/isr.svg",
            "isActive": true
        },
        {
            "id": 113,
            "country": "Italy",
            "callingCode": "39",
            "countryCode": "ITA",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/ita.svg",
            "isActive": true
        },
        {
            "id": 114,
            "country": "Jamaica",
            "callingCode": "1876",
            "countryCode": "JAM",
            "currencyCode": "JMD",
            "currencyName": "Jamaican dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/jam.svg",
            "isActive": true
        },
        {
            "id": 115,
            "country": "Japan",
            "callingCode": "81",
            "countryCode": "JPN",
            "currencyCode": "JPY",
            "currencyName": "Japanese yen",
            "curencySymbol": "¥",
            "flag": "54.89.97.147:3002/static/data/jpn.svg",
            "isActive": true
        },
        {
            "id": 116,
            "country": "Jersey",
            "callingCode": "44",
            "countryCode": "JEY",
            "currencyCode": "GBP",
            "currencyName": "British pound",
            "curencySymbol": "£",
            "flag": "54.89.97.147:3002/static/data/jey.svg",
            "isActive": true
        },
        {
            "id": 117,
            "country": "Jordan",
            "callingCode": "962",
            "countryCode": "JOR",
            "currencyCode": "JOD",
            "currencyName": "Jordanian dinar",
            "curencySymbol": "د.ا",
            "flag": "54.89.97.147:3002/static/data/jor.svg",
            "isActive": true
        },
        {
            "id": 118,
            "country": "Kazakhstan",
            "callingCode": "76",
            "countryCode": "KAZ",
            "currencyCode": "KZT",
            "currencyName": "Kazakhstani tenge",
            "curencySymbol": null,
            "flag": "54.89.97.147:3002/static/data/kaz.svg",
            "isActive": true
        },
        {
            "id": 119,
            "country": "Kenya",
            "callingCode": "254",
            "countryCode": "KEN",
            "currencyCode": "KES",
            "currencyName": "Kenyan shilling",
            "curencySymbol": "Sh",
            "flag": "54.89.97.147:3002/static/data/ken.svg",
            "isActive": true
        },
        {
            "id": 120,
            "country": "Kiribati",
            "callingCode": "686",
            "countryCode": "KIR",
            "currencyCode": "AUD",
            "currencyName": "Australian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/kir.svg",
            "isActive": true
        },
        {
            "id": 166,
            "country": "Korea (Democratic People's Republic of)",
            "callingCode": "850",
            "countryCode": "PRK",
            "currencyCode": "KPW",
            "currencyName": "North Korean won",
            "curencySymbol": "₩",
            "flag": "54.89.97.147:3002/static/data/prk.svg",
            "isActive": true
        },
        {
            "id": 259,
            "country": "Korea (North)",
            "callingCode": "+0",
            "countryCode": "Korea (North)",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 211,
            "country": "Korea (Republic of)",
            "callingCode": "82",
            "countryCode": "KOR",
            "currencyCode": "KRW",
            "currencyName": "South Korean won",
            "curencySymbol": "₩",
            "flag": "54.89.97.147:3002/static/data/kor.svg",
            "isActive": true
        },
        {
            "id": 260,
            "country": "Korea (South)",
            "callingCode": "82",
            "countryCode": "Korea (South)",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 121,
            "country": "Kuwait",
            "callingCode": "965",
            "countryCode": "KWT",
            "currencyCode": "KWD",
            "currencyName": "Kuwaiti dinar",
            "curencySymbol": "د.ك",
            "flag": "54.89.97.147:3002/static/data/kwt.svg",
            "isActive": true
        },
        {
            "id": 122,
            "country": "Kyrgyzstan",
            "callingCode": "996",
            "countryCode": "KGZ",
            "currencyCode": "KGS",
            "currencyName": "Kyrgyzstani som",
            "curencySymbol": "с",
            "flag": "54.89.97.147:3002/static/data/kgz.svg",
            "isActive": true
        },
        {
            "id": 123,
            "country": "Lao People's Democratic Republic",
            "callingCode": "856",
            "countryCode": "LAO",
            "currencyCode": "LAK",
            "currencyName": "Lao kip",
            "curencySymbol": "₭",
            "flag": "54.89.97.147:3002/static/data/lao.svg",
            "isActive": true
        },
        {
            "id": 124,
            "country": "Latvia",
            "callingCode": "371",
            "countryCode": "LVA",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/lva.svg",
            "isActive": true
        },
        {
            "id": 125,
            "country": "Lebanon",
            "callingCode": "961",
            "countryCode": "LBN",
            "currencyCode": "LBP",
            "currencyName": "Lebanese pound",
            "curencySymbol": "ل.ل",
            "flag": "54.89.97.147:3002/static/data/lbn.svg",
            "isActive": true
        },
        {
            "id": 126,
            "country": "Lesotho",
            "callingCode": "266",
            "countryCode": "LSO",
            "currencyCode": "LSL",
            "currencyName": "Lesotho loti",
            "curencySymbol": "L",
            "flag": "54.89.97.147:3002/static/data/lso.svg",
            "isActive": true
        },
        {
            "id": 127,
            "country": "Liberia",
            "callingCode": "231",
            "countryCode": "LBR",
            "currencyCode": "LRD",
            "currencyName": "Liberian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/lbr.svg",
            "isActive": true
        },
        {
            "id": 128,
            "country": "Libya",
            "callingCode": "218",
            "countryCode": "LBY",
            "currencyCode": "LYD",
            "currencyName": "Libyan dinar",
            "curencySymbol": "ل.د",
            "flag": "54.89.97.147:3002/static/data/lby.svg",
            "isActive": true
        },
        {
            "id": 129,
            "country": "Liechtenstein",
            "callingCode": "423",
            "countryCode": "LIE",
            "currencyCode": "CHF",
            "currencyName": "Swiss franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/lie.svg",
            "isActive": true
        },
        {
            "id": 130,
            "country": "Lithuania",
            "callingCode": "370",
            "countryCode": "LTU",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/ltu.svg",
            "isActive": true
        },
        {
            "id": 131,
            "country": "Luxembourg",
            "callingCode": "352",
            "countryCode": "LUX",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/lux.svg",
            "isActive": true
        },
        {
            "id": 132,
            "country": "Macao",
            "callingCode": "853",
            "countryCode": "MAC",
            "currencyCode": "MOP",
            "currencyName": "Macanese pataca",
            "curencySymbol": "P",
            "flag": "54.89.97.147:3002/static/data/mac.svg",
            "isActive": true
        },
        {
            "id": 261,
            "country": "Macau",
            "callingCode": "853",
            "countryCode": "Macau",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 133,
            "country": "Macedonia (the former Yugoslav Republic of)",
            "callingCode": "389",
            "countryCode": "MKD",
            "currencyCode": "MKD",
            "currencyName": "Macedonian denar",
            "curencySymbol": "ден",
            "flag": "54.89.97.147:3002/static/data/mkd.svg",
            "isActive": true
        },
        {
            "id": 134,
            "country": "Madagascar",
            "callingCode": "261",
            "countryCode": "MDG",
            "currencyCode": "MGA",
            "currencyName": "Malagasy ariary",
            "curencySymbol": "Ar",
            "flag": "54.89.97.147:3002/static/data/mdg.svg",
            "isActive": true
        },
        {
            "id": 135,
            "country": "Malawi",
            "callingCode": "265",
            "countryCode": "MWI",
            "currencyCode": "MWK",
            "currencyName": "Malawian kwacha",
            "curencySymbol": "MK",
            "flag": "54.89.97.147:3002/static/data/mwi.svg",
            "isActive": true
        },
        {
            "id": 136,
            "country": "Malaysia",
            "callingCode": "60",
            "countryCode": "MYS",
            "currencyCode": "MYR",
            "currencyName": "Malaysian ringgit",
            "curencySymbol": "RM",
            "flag": "54.89.97.147:3002/static/data/mys.svg",
            "isActive": true
        },
        {
            "id": 137,
            "country": "Maldives",
            "callingCode": "960",
            "countryCode": "MDV",
            "currencyCode": "MVR",
            "currencyName": "Maldivian rufiyaa",
            "curencySymbol": ".ރ",
            "flag": "54.89.97.147:3002/static/data/mdv.svg",
            "isActive": true
        },
        {
            "id": 138,
            "country": "Mali",
            "callingCode": "223",
            "countryCode": "MLI",
            "currencyCode": "XOF",
            "currencyName": "West African CFA franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/mli.svg",
            "isActive": true
        },
        {
            "id": 139,
            "country": "Malta",
            "callingCode": "356",
            "countryCode": "MLT",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/mlt.svg",
            "isActive": true
        },
        {
            "id": 140,
            "country": "Marshall Islands",
            "callingCode": "692",
            "countryCode": "MHL",
            "currencyCode": "USD",
            "currencyName": "United States dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/mhl.svg",
            "isActive": true
        },
        {
            "id": 141,
            "country": "Martinique",
            "callingCode": "596",
            "countryCode": "MTQ",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/mtq.svg",
            "isActive": true
        },
        {
            "id": 142,
            "country": "Mauritania",
            "callingCode": "222",
            "countryCode": "MRT",
            "currencyCode": "MRO",
            "currencyName": "Mauritanian ouguiya",
            "curencySymbol": "UM",
            "flag": "54.89.97.147:3002/static/data/mrt.svg",
            "isActive": true
        },
        {
            "id": 143,
            "country": "Mauritius",
            "callingCode": "230",
            "countryCode": "MUS",
            "currencyCode": "MUR",
            "currencyName": "Mauritian rupee",
            "curencySymbol": "₨",
            "flag": "54.89.97.147:3002/static/data/mus.svg",
            "isActive": true
        },
        {
            "id": 144,
            "country": "Mayotte",
            "callingCode": "262",
            "countryCode": "MYT",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/myt.svg",
            "isActive": true
        },
        {
            "id": 145,
            "country": "Mexico",
            "callingCode": "52",
            "countryCode": "MEX",
            "currencyCode": "MXN",
            "currencyName": "Mexican peso",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/mex.svg",
            "isActive": true
        },
        {
            "id": 262,
            "country": "Micronesia",
            "callingCode": "691",
            "countryCode": "Micronesia",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 146,
            "country": "Micronesia (Federated States of)",
            "callingCode": "691",
            "countryCode": "FSM",
            "currencyCode": null,
            "currencyName": "[D]",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/fsm.svg",
            "isActive": true
        },
        {
            "id": 147,
            "country": "Moldova (Republic of)",
            "callingCode": "373",
            "countryCode": "MDA",
            "currencyCode": "MDL",
            "currencyName": "Moldovan leu",
            "curencySymbol": "L",
            "flag": "54.89.97.147:3002/static/data/mda.svg",
            "isActive": true
        },
        {
            "id": 148,
            "country": "Monaco",
            "callingCode": "377",
            "countryCode": "MCO",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/mco.svg",
            "isActive": true
        },
        {
            "id": 149,
            "country": "Mongolia",
            "callingCode": "976",
            "countryCode": "MNG",
            "currencyCode": "MNT",
            "currencyName": "Mongolian tögrög",
            "curencySymbol": "₮",
            "flag": "54.89.97.147:3002/static/data/mng.svg",
            "isActive": true
        },
        {
            "id": 150,
            "country": "Montenegro",
            "callingCode": "382",
            "countryCode": "MNE",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/mne.svg",
            "isActive": true
        },
        {
            "id": 151,
            "country": "Montserrat",
            "callingCode": "1664",
            "countryCode": "MSR",
            "currencyCode": "XCD",
            "currencyName": "East Caribbean dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/msr.svg",
            "isActive": true
        },
        {
            "id": 152,
            "country": "Morocco",
            "callingCode": "212",
            "countryCode": "MAR",
            "currencyCode": "MAD",
            "currencyName": "Moroccan dirham",
            "curencySymbol": "د.م.",
            "flag": "54.89.97.147:3002/static/data/mar.svg",
            "isActive": true
        },
        {
            "id": 153,
            "country": "Mozambique",
            "callingCode": "258",
            "countryCode": "MOZ",
            "currencyCode": "MZN",
            "currencyName": "Mozambican metical",
            "curencySymbol": "MT",
            "flag": "54.89.97.147:3002/static/data/moz.svg",
            "isActive": true
        },
        {
            "id": 154,
            "country": "Myanmar",
            "callingCode": "95",
            "countryCode": "MMR",
            "currencyCode": "MMK",
            "currencyName": "Burmese kyat",
            "curencySymbol": "Ks",
            "flag": "54.89.97.147:3002/static/data/mmr.svg",
            "isActive": true
        },
        {
            "id": 155,
            "country": "Namibia",
            "callingCode": "264",
            "countryCode": "NAM",
            "currencyCode": "NAD",
            "currencyName": "Namibian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/nam.svg",
            "isActive": true
        },
        {
            "id": 156,
            "country": "Nauru",
            "callingCode": "674",
            "countryCode": "NRU",
            "currencyCode": "AUD",
            "currencyName": "Australian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/nru.svg",
            "isActive": true
        },
        {
            "id": 157,
            "country": "Nepal",
            "callingCode": "977",
            "countryCode": "NPL",
            "currencyCode": "NPR",
            "currencyName": "Nepalese rupee",
            "curencySymbol": "₨",
            "flag": "54.89.97.147:3002/static/data/npl.svg",
            "isActive": true
        },
        {
            "id": 158,
            "country": "Netherlands",
            "callingCode": "31",
            "countryCode": "NLD",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/nld.svg",
            "isActive": true
        },
        {
            "id": 263,
            "country": "Netherlands\nAntilles",
            "callingCode": "",
            "countryCode": "Netherlands\nAntilles",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 159,
            "country": "New Caledonia",
            "callingCode": "687",
            "countryCode": "NCL",
            "currencyCode": "XPF",
            "currencyName": "CFP franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/ncl.svg",
            "isActive": true
        },
        {
            "id": 160,
            "country": "New Zealand",
            "callingCode": "64",
            "countryCode": "NZL",
            "currencyCode": "NZD",
            "currencyName": "New Zealand dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/nzl.svg",
            "isActive": true
        },
        {
            "id": 161,
            "country": "Nicaragua",
            "callingCode": "505",
            "countryCode": "NIC",
            "currencyCode": "NIO",
            "currencyName": "Nicaraguan córdoba",
            "curencySymbol": "C$",
            "flag": "54.89.97.147:3002/static/data/nic.svg",
            "isActive": true
        },
        {
            "id": 162,
            "country": "Niger",
            "callingCode": "227",
            "countryCode": "NER",
            "currencyCode": "XOF",
            "currencyName": "West African CFA franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/ner.svg",
            "isActive": true
        },
        {
            "id": 163,
            "country": "Nigeria",
            "callingCode": "234",
            "countryCode": "NGA",
            "currencyCode": "NGN",
            "currencyName": "Nigerian naira",
            "curencySymbol": "₦",
            "flag": "54.89.97.147:3002/static/data/nga.svg",
            "isActive": true
        },
        {
            "id": 164,
            "country": "Niue",
            "callingCode": "683",
            "countryCode": "NIU",
            "currencyCode": "NZD",
            "currencyName": "New Zealand dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/niu.svg",
            "isActive": true
        },
        {
            "id": 165,
            "country": "Norfolk Island",
            "callingCode": "672",
            "countryCode": "NFK",
            "currencyCode": "AUD",
            "currencyName": "Australian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/nfk.svg",
            "isActive": true
        },
        {
            "id": 264,
            "country": "Northern Mariana\nIslands",
            "callingCode": "1",
            "countryCode": "Northern Mariana\nIslands",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 167,
            "country": "Northern Mariana Islands",
            "callingCode": "1670",
            "countryCode": "MNP",
            "currencyCode": "USD",
            "currencyName": "United States dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/mnp.svg",
            "isActive": true
        },
        {
            "id": 168,
            "country": "Norway",
            "callingCode": "47",
            "countryCode": "NOR",
            "currencyCode": "NOK",
            "currencyName": "Norwegian krone",
            "curencySymbol": "kr",
            "flag": "54.89.97.147:3002/static/data/nor.svg",
            "isActive": true
        },
        {
            "id": 169,
            "country": "Oman",
            "callingCode": "968",
            "countryCode": "OMN",
            "currencyCode": "OMR",
            "currencyName": "Omani rial",
            "curencySymbol": "ر.ع.",
            "flag": "54.89.97.147:3002/static/data/omn.svg",
            "isActive": true
        },
        {
            "id": 170,
            "country": "Pakistan",
            "callingCode": "92",
            "countryCode": "PAK",
            "currencyCode": "PKR",
            "currencyName": "Pakistani rupee",
            "curencySymbol": "₨",
            "flag": "54.89.97.147:3002/static/data/pak.svg",
            "isActive": true
        },
        {
            "id": 171,
            "country": "Palau",
            "callingCode": "680",
            "countryCode": "PLW",
            "currencyCode": "(none)",
            "currencyName": "[E]",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/plw.svg",
            "isActive": true
        },
        {
            "id": 172,
            "country": "Palestine, State of",
            "callingCode": "970",
            "countryCode": "PSE",
            "currencyCode": "ILS",
            "currencyName": "Israeli new sheqel",
            "curencySymbol": "₪",
            "flag": "54.89.97.147:3002/static/data/pse.svg",
            "isActive": true
        },
        {
            "id": 173,
            "country": "Panama",
            "callingCode": "507",
            "countryCode": "PAN",
            "currencyCode": "PAB",
            "currencyName": "Panamanian balboa",
            "curencySymbol": "B/.",
            "flag": "54.89.97.147:3002/static/data/pan.svg",
            "isActive": true
        },
        {
            "id": 265,
            "country": "Papua New\nGuinea",
            "callingCode": "675",
            "countryCode": "Papua New\nGuinea",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 174,
            "country": "Papua New Guinea",
            "callingCode": "675",
            "countryCode": "PNG",
            "currencyCode": "PGK",
            "currencyName": "Papua New Guinean kina",
            "curencySymbol": "K",
            "flag": "54.89.97.147:3002/static/data/png.svg",
            "isActive": true
        },
        {
            "id": 175,
            "country": "Paraguay",
            "callingCode": "595",
            "countryCode": "PRY",
            "currencyCode": "PYG",
            "currencyName": "Paraguayan guaraní",
            "curencySymbol": "₲",
            "flag": "54.89.97.147:3002/static/data/pry.svg",
            "isActive": true
        },
        {
            "id": 176,
            "country": "Peru",
            "callingCode": "51",
            "countryCode": "PER",
            "currencyCode": "PEN",
            "currencyName": "Peruvian sol",
            "curencySymbol": "S/.",
            "flag": "54.89.97.147:3002/static/data/per.svg",
            "isActive": true
        },
        {
            "id": 177,
            "country": "Philippines",
            "callingCode": "63",
            "countryCode": "PHL",
            "currencyCode": "PHP",
            "currencyName": "Philippine peso",
            "curencySymbol": "₱",
            "flag": "54.89.97.147:3002/static/data/phl.svg",
            "isActive": true
        },
        {
            "id": 178,
            "country": "Pitcairn",
            "callingCode": "64",
            "countryCode": "PCN",
            "currencyCode": "NZD",
            "currencyName": "New Zealand dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/pcn.svg",
            "isActive": true
        },
        {
            "id": 179,
            "country": "Poland",
            "callingCode": "48",
            "countryCode": "POL",
            "currencyCode": "PLN",
            "currencyName": "Polish złoty",
            "curencySymbol": "zł",
            "flag": "54.89.97.147:3002/static/data/pol.svg",
            "isActive": true
        },
        {
            "id": 180,
            "country": "Portugal",
            "callingCode": "351",
            "countryCode": "PRT",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/prt.svg",
            "isActive": true
        },
        {
            "id": 181,
            "country": "Puerto Rico",
            "callingCode": "1787",
            "countryCode": "PRI",
            "currencyCode": "USD",
            "currencyName": "United States dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/pri.svg",
            "isActive": true
        },
        {
            "id": 182,
            "country": "Qatar",
            "callingCode": "974",
            "countryCode": "QAT",
            "currencyCode": "QAR",
            "currencyName": "Qatari riyal",
            "curencySymbol": "ر.ق",
            "flag": "54.89.97.147:3002/static/data/qat.svg",
            "isActive": true
        },
        {
            "id": 183,
            "country": "Republic of Kosovo",
            "callingCode": "383",
            "countryCode": "KOS",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/kos.svg",
            "isActive": true
        },
        {
            "id": 266,
            "country": "Reunion",
            "callingCode": "262",
            "countryCode": "Reunion",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 185,
            "country": "Romania",
            "callingCode": "40",
            "countryCode": "ROU",
            "currencyCode": "RON",
            "currencyName": "Romanian leu",
            "curencySymbol": "lei",
            "flag": "54.89.97.147:3002/static/data/rou.svg",
            "isActive": true
        },
        {
            "id": 267,
            "country": "Russia",
            "callingCode": "7",
            "countryCode": "Russia",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 186,
            "country": "Russian Federation",
            "callingCode": "7",
            "countryCode": "RUS",
            "currencyCode": "RUB",
            "currencyName": "Russian ruble",
            "curencySymbol": "₽",
            "flag": "54.89.97.147:3002/static/data/rus.svg",
            "isActive": true
        },
        {
            "id": 187,
            "country": "Rwanda",
            "callingCode": "250",
            "countryCode": "RWA",
            "currencyCode": "RWF",
            "currencyName": "Rwandan franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/rwa.svg",
            "isActive": true
        },
        {
            "id": 184,
            "country": "Réunion",
            "callingCode": "262",
            "countryCode": "REU",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/reu.svg",
            "isActive": true
        },
        {
            "id": 188,
            "country": "Saint Barthélemy",
            "callingCode": "590",
            "countryCode": "BLM",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/blm.svg",
            "isActive": true
        },
        {
            "id": 189,
            "country": "Saint Helena, Ascension and Tristan da Cunha",
            "callingCode": "290",
            "countryCode": "SHN",
            "currencyCode": "SHP",
            "currencyName": "Saint Helena pound",
            "curencySymbol": "£",
            "flag": "54.89.97.147:3002/static/data/shn.svg",
            "isActive": true
        },
        {
            "id": 268,
            "country": "Saint Kitts and\nNevis",
            "callingCode": "+0",
            "countryCode": "Saint Kitts and\nNevis",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 190,
            "country": "Saint Kitts and Nevis",
            "callingCode": "1869",
            "countryCode": "KNA",
            "currencyCode": "XCD",
            "currencyName": "East Caribbean dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/kna.svg",
            "isActive": true
        },
        {
            "id": 191,
            "country": "Saint Lucia",
            "callingCode": "1758",
            "countryCode": "LCA",
            "currencyCode": "XCD",
            "currencyName": "East Caribbean dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/lca.svg",
            "isActive": true
        },
        {
            "id": 192,
            "country": "Saint Martin (French part)",
            "callingCode": "590",
            "countryCode": "MAF",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/maf.svg",
            "isActive": true
        },
        {
            "id": 193,
            "country": "Saint Pierre and Miquelon",
            "callingCode": "508",
            "countryCode": "SPM",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/spm.svg",
            "isActive": true
        },
        {
            "id": 269,
            "country": "Saint Vincent and\nthe Grenadines",
            "callingCode": "1",
            "countryCode": "Saint Vincent and\nthe Grenadines",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 194,
            "country": "Saint Vincent and the Grenadines",
            "callingCode": "1784",
            "countryCode": "VCT",
            "currencyCode": "XCD",
            "currencyName": "East Caribbean dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/vct.svg",
            "isActive": true
        },
        {
            "id": 195,
            "country": "Samoa",
            "callingCode": "685",
            "countryCode": "WSM",
            "currencyCode": "WST",
            "currencyName": "Samoan tālā",
            "curencySymbol": "T",
            "flag": "54.89.97.147:3002/static/data/wsm.svg",
            "isActive": true
        },
        {
            "id": 196,
            "country": "San Marino",
            "callingCode": "378",
            "countryCode": "SMR",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/smr.svg",
            "isActive": true
        },
        {
            "id": 270,
            "country": "Sao Tome and\nPrincipe",
            "callingCode": "+0",
            "countryCode": "Sao Tome and\nPrincipe",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 197,
            "country": "Sao Tome and Principe",
            "callingCode": "239",
            "countryCode": "STP",
            "currencyCode": "STD",
            "currencyName": "São Tomé and Príncipe dobra",
            "curencySymbol": "Db",
            "flag": "54.89.97.147:3002/static/data/stp.svg",
            "isActive": true
        },
        {
            "id": 198,
            "country": "Saudi Arabia",
            "callingCode": "966",
            "countryCode": "SAU",
            "currencyCode": "SAR",
            "currencyName": "Saudi riyal",
            "curencySymbol": "ر.س",
            "flag": "54.89.97.147:3002/static/data/sau.svg",
            "isActive": true
        },
        {
            "id": 199,
            "country": "Senegal",
            "callingCode": "221",
            "countryCode": "SEN",
            "currencyCode": "XOF",
            "currencyName": "West African CFA franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/sen.svg",
            "isActive": true
        },
        {
            "id": 200,
            "country": "Serbia",
            "callingCode": "381",
            "countryCode": "SRB",
            "currencyCode": "RSD",
            "currencyName": "Serbian dinar",
            "curencySymbol": "дин.",
            "flag": "54.89.97.147:3002/static/data/srb.svg",
            "isActive": true
        },
        {
            "id": 201,
            "country": "Seychelles",
            "callingCode": "248",
            "countryCode": "SYC",
            "currencyCode": "SCR",
            "currencyName": "Seychellois rupee",
            "curencySymbol": "₨",
            "flag": "54.89.97.147:3002/static/data/syc.svg",
            "isActive": true
        },
        {
            "id": 202,
            "country": "Sierra Leone",
            "callingCode": "232",
            "countryCode": "SLE",
            "currencyCode": "SLL",
            "currencyName": "Sierra Leonean leone",
            "curencySymbol": "Le",
            "flag": "54.89.97.147:3002/static/data/sle.svg",
            "isActive": true
        },
        {
            "id": 203,
            "country": "Singapore",
            "callingCode": "65",
            "countryCode": "SGP",
            "currencyCode": "BND",
            "currencyName": "Brunei dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/sgp.svg",
            "isActive": true
        },
        {
            "id": 204,
            "country": "Sint Maarten (Dutch part)",
            "callingCode": "1721",
            "countryCode": "SXM",
            "currencyCode": "ANG",
            "currencyName": "Netherlands Antillean guilder",
            "curencySymbol": "ƒ",
            "flag": "54.89.97.147:3002/static/data/sxm.svg",
            "isActive": true
        },
        {
            "id": 205,
            "country": "Slovakia",
            "callingCode": "421",
            "countryCode": "SVK",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/svk.svg",
            "isActive": true
        },
        {
            "id": 206,
            "country": "Slovenia",
            "callingCode": "386",
            "countryCode": "SVN",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/svn.svg",
            "isActive": true
        },
        {
            "id": 207,
            "country": "Solomon Islands",
            "callingCode": "677",
            "countryCode": "SLB",
            "currencyCode": "SBD",
            "currencyName": "Solomon Islands dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/slb.svg",
            "isActive": true
        },
        {
            "id": 208,
            "country": "Somalia",
            "callingCode": "252",
            "countryCode": "SOM",
            "currencyCode": "SOS",
            "currencyName": "Somali shilling",
            "curencySymbol": "Sh",
            "flag": "54.89.97.147:3002/static/data/som.svg",
            "isActive": true
        },
        {
            "id": 209,
            "country": "South Africa",
            "callingCode": "27",
            "countryCode": "ZAF",
            "currencyCode": "ZAR",
            "currencyName": "South African rand",
            "curencySymbol": "R",
            "flag": "54.89.97.147:3002/static/data/zaf.svg",
            "isActive": true
        },
        {
            "id": 210,
            "country": "South Georgia and the South Sandwich Islands",
            "callingCode": "500",
            "countryCode": "SGS",
            "currencyCode": "GBP",
            "currencyName": "British pound",
            "curencySymbol": "£",
            "flag": "54.89.97.147:3002/static/data/sgs.svg",
            "isActive": true
        },
        {
            "id": 212,
            "country": "South Sudan",
            "callingCode": "211",
            "countryCode": "SSD",
            "currencyCode": "SSP",
            "currencyName": "South Sudanese pound",
            "curencySymbol": "£",
            "flag": "54.89.97.147:3002/static/data/ssd.svg",
            "isActive": true
        },
        {
            "id": 213,
            "country": "Spain",
            "callingCode": "34",
            "countryCode": "ESP",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/esp.svg",
            "isActive": true
        },
        {
            "id": 214,
            "country": "Sri Lanka",
            "callingCode": "94",
            "countryCode": "LKA",
            "currencyCode": "LKR",
            "currencyName": "Sri Lankan rupee",
            "curencySymbol": "Rs",
            "flag": "54.89.97.147:3002/static/data/lka.svg",
            "isActive": true
        },
        {
            "id": 271,
            "country": "St. Helena",
            "callingCode": "+0",
            "countryCode": "St. Helena",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 272,
            "country": "St. Pierre and\nMiquelon",
            "callingCode": "508",
            "countryCode": "St. Pierre and\nMiquelon",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 215,
            "country": "Sudan",
            "callingCode": "249",
            "countryCode": "SDN",
            "currencyCode": "SDG",
            "currencyName": "Sudanese pound",
            "curencySymbol": "ج.س.",
            "flag": "54.89.97.147:3002/static/data/sdn.svg",
            "isActive": true
        },
        {
            "id": 216,
            "country": "Suriname",
            "callingCode": "597",
            "countryCode": "SUR",
            "currencyCode": "SRD",
            "currencyName": "Surinamese dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/sur.svg",
            "isActive": true
        },
        {
            "id": 217,
            "country": "Svalbard and Jan Mayen",
            "callingCode": "4779",
            "countryCode": "SJM",
            "currencyCode": "NOK",
            "currencyName": "Norwegian krone",
            "curencySymbol": "kr",
            "flag": "54.89.97.147:3002/static/data/sjm.svg",
            "isActive": true
        },
        {
            "id": 218,
            "country": "Swaziland",
            "callingCode": "268",
            "countryCode": "SWZ",
            "currencyCode": "SZL",
            "currencyName": "Swazi lilangeni",
            "curencySymbol": "L",
            "flag": "54.89.97.147:3002/static/data/swz.svg",
            "isActive": true
        },
        {
            "id": 219,
            "country": "Sweden",
            "callingCode": "46",
            "countryCode": "SWE",
            "currencyCode": "SEK",
            "currencyName": "Swedish krona",
            "curencySymbol": "kr",
            "flag": "54.89.97.147:3002/static/data/swe.svg",
            "isActive": true
        },
        {
            "id": 220,
            "country": "Switzerland",
            "callingCode": "41",
            "countryCode": "CHE",
            "currencyCode": "CHF",
            "currencyName": "Swiss franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/che.svg",
            "isActive": true
        },
        {
            "id": 273,
            "country": "Syria",
            "callingCode": "963",
            "countryCode": "Syria",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 221,
            "country": "Syrian Arab Republic",
            "callingCode": "963",
            "countryCode": "SYR",
            "currencyCode": "SYP",
            "currencyName": "Syrian pound",
            "curencySymbol": "£",
            "flag": "54.89.97.147:3002/static/data/syr.svg",
            "isActive": true
        },
        {
            "id": 222,
            "country": "Taiwan",
            "callingCode": "886",
            "countryCode": "TWN",
            "currencyCode": "TWD",
            "currencyName": "New Taiwan dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/twn.svg",
            "isActive": true
        },
        {
            "id": 223,
            "country": "Tajikistan",
            "callingCode": "992",
            "countryCode": "TJK",
            "currencyCode": "TJS",
            "currencyName": "Tajikistani somoni",
            "curencySymbol": "ЅМ",
            "flag": "54.89.97.147:3002/static/data/tjk.svg",
            "isActive": true
        },
        {
            "id": 274,
            "country": "Tanzania",
            "callingCode": "255",
            "countryCode": "Tanzania",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 224,
            "country": "Tanzania, United Republic of",
            "callingCode": "255",
            "countryCode": "TZA",
            "currencyCode": "TZS",
            "currencyName": "Tanzanian shilling",
            "curencySymbol": "Sh",
            "flag": "54.89.97.147:3002/static/data/tza.svg",
            "isActive": true
        },
        {
            "id": 225,
            "country": "Thailand",
            "callingCode": "66",
            "countryCode": "THA",
            "currencyCode": "THB",
            "currencyName": "Thai baht",
            "curencySymbol": "฿",
            "flag": "54.89.97.147:3002/static/data/tha.svg",
            "isActive": true
        },
        {
            "id": 226,
            "country": "Timor-Leste",
            "callingCode": "670",
            "countryCode": "TLS",
            "currencyCode": "USD",
            "currencyName": "United States dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/tls.svg",
            "isActive": true
        },
        {
            "id": 227,
            "country": "Togo",
            "callingCode": "228",
            "countryCode": "TGO",
            "currencyCode": "XOF",
            "currencyName": "West African CFA franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/tgo.svg",
            "isActive": true
        },
        {
            "id": 228,
            "country": "Tokelau",
            "callingCode": "690",
            "countryCode": "TKL",
            "currencyCode": "NZD",
            "currencyName": "New Zealand dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/tkl.svg",
            "isActive": true
        },
        {
            "id": 229,
            "country": "Tonga",
            "callingCode": "676",
            "countryCode": "TON",
            "currencyCode": "TOP",
            "currencyName": "Tongan paʻanga",
            "curencySymbol": "T$",
            "flag": "54.89.97.147:3002/static/data/ton.svg",
            "isActive": true
        },
        {
            "id": 275,
            "country": "Trinidad and\nTobago",
            "callingCode": "1",
            "countryCode": "Trinidad and\nTobago",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 230,
            "country": "Trinidad and Tobago",
            "callingCode": "1868",
            "countryCode": "TTO",
            "currencyCode": "TTD",
            "currencyName": "Trinidad and Tobago dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/tto.svg",
            "isActive": true
        },
        {
            "id": 231,
            "country": "Tunisia",
            "callingCode": "216",
            "countryCode": "TUN",
            "currencyCode": "TND",
            "currencyName": "Tunisian dinar",
            "curencySymbol": "د.ت",
            "flag": "54.89.97.147:3002/static/data/tun.svg",
            "isActive": true
        },
        {
            "id": 232,
            "country": "Turkey",
            "callingCode": "90",
            "countryCode": "TUR",
            "currencyCode": "TRY",
            "currencyName": "Turkish lira",
            "curencySymbol": null,
            "flag": "54.89.97.147:3002/static/data/tur.svg",
            "isActive": true
        },
        {
            "id": 233,
            "country": "Turkmenistan",
            "callingCode": "993",
            "countryCode": "TKM",
            "currencyCode": "TMT",
            "currencyName": "Turkmenistan manat",
            "curencySymbol": "m",
            "flag": "54.89.97.147:3002/static/data/tkm.svg",
            "isActive": true
        },
        {
            "id": 276,
            "country": "Turks and Caicos\nIslands",
            "callingCode": "1",
            "countryCode": "Turks and Caicos\nIslands",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 234,
            "country": "Turks and Caicos Islands",
            "callingCode": "1649",
            "countryCode": "TCA",
            "currencyCode": "USD",
            "currencyName": "United States dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/tca.svg",
            "isActive": true
        },
        {
            "id": 235,
            "country": "Tuvalu",
            "callingCode": "688",
            "countryCode": "TUV",
            "currencyCode": "AUD",
            "currencyName": "Australian dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/tuv.svg",
            "isActive": true
        },
        {
            "id": 236,
            "country": "Uganda",
            "callingCode": "256",
            "countryCode": "UGA",
            "currencyCode": "UGX",
            "currencyName": "Ugandan shilling",
            "curencySymbol": "Sh",
            "flag": "54.89.97.147:3002/static/data/uga.svg",
            "isActive": true
        },
        {
            "id": 237,
            "country": "Ukraine",
            "callingCode": "380",
            "countryCode": "UKR",
            "currencyCode": "UAH",
            "currencyName": "Ukrainian hryvnia",
            "curencySymbol": "₴",
            "flag": "54.89.97.147:3002/static/data/ukr.svg",
            "isActive": true
        },
        {
            "id": 278,
            "country": "United Arab\nEmirates",
            "callingCode": "971",
            "countryCode": "United Arab\nEmirates",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 238,
            "country": "United Arab Emirates",
            "callingCode": "971",
            "countryCode": "ARE",
            "currencyCode": "AED",
            "currencyName": "United Arab Emirates dirham",
            "curencySymbol": "د.إ",
            "flag": "54.89.97.147:3002/static/data/are.svg",
            "isActive": true
        },
        {
            "id": 277,
            "country": "United Kingdom",
            "callingCode": "44",
            "countryCode": "United Kingdom",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 239,
            "country": "United Kingdom of Great Britain and Northern Ireland",
            "callingCode": "44",
            "countryCode": "GBR",
            "currencyCode": "GBP",
            "currencyName": "British pound",
            "curencySymbol": "£",
            "flag": "54.89.97.147:3002/static/data/gbr.svg",
            "isActive": true
        },
        {
            "id": 279,
            "country": "United States",
            "callingCode": "1",
            "countryCode": "United States",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 34,
            "country": "United States Minor Outlying Islands",
            "callingCode": "",
            "countryCode": "UMI",
            "currencyCode": "USD",
            "currencyName": "United States Dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/umi.svg",
            "isActive": true
        },
        {
            "id": 240,
            "country": "United States of America",
            "callingCode": "1",
            "countryCode": "USA",
            "currencyCode": "USD",
            "currencyName": "United States dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/usa.svg",
            "isActive": true
        },
        {
            "id": 241,
            "country": "Uruguay",
            "callingCode": "598",
            "countryCode": "URY",
            "currencyCode": "UYU",
            "currencyName": "Uruguayan peso",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/ury.svg",
            "isActive": true
        },
        {
            "id": 242,
            "country": "Uzbekistan",
            "callingCode": "998",
            "countryCode": "UZB",
            "currencyCode": "UZS",
            "currencyName": "Uzbekistani so'm",
            "curencySymbol": null,
            "flag": "54.89.97.147:3002/static/data/uzb.svg",
            "isActive": true
        },
        {
            "id": 243,
            "country": "Vanuatu",
            "callingCode": "678",
            "countryCode": "VUT",
            "currencyCode": "VUV",
            "currencyName": "Vanuatu vatu",
            "curencySymbol": "Vt",
            "flag": "54.89.97.147:3002/static/data/vut.svg",
            "isActive": true
        },
        {
            "id": 280,
            "country": "Venezuela",
            "callingCode": "58",
            "countryCode": "Venezuela",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 244,
            "country": "Venezuela (Bolivarian Republic of)",
            "callingCode": "58",
            "countryCode": "VEN",
            "currencyCode": "VEF",
            "currencyName": "Venezuelan bolívar",
            "curencySymbol": "Bs F",
            "flag": "54.89.97.147:3002/static/data/ven.svg",
            "isActive": true
        },
        {
            "id": 245,
            "country": "Viet Nam",
            "callingCode": "84",
            "countryCode": "VNM",
            "currencyCode": "VND",
            "currencyName": "Vietnamese đồng",
            "curencySymbol": "₫",
            "flag": "54.89.97.147:3002/static/data/vnm.svg",
            "isActive": true
        },
        {
            "id": 281,
            "country": "Vietnam",
            "callingCode": "84",
            "countryCode": "Vietnam",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 282,
            "country": "Virgin Isl. (US)",
            "callingCode": "1",
            "countryCode": "Virgin Isl. (US)",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 283,
            "country": "Virgin Islands\n(US)",
            "callingCode": "1",
            "countryCode": "Virgin Islands\n(US)",
            "currencyCode": null,
            "currencyName": null,
            "curencySymbol": null,
            "flag": null,
            "isActive": true
        },
        {
            "id": 35,
            "country": "Virgin Islands (British)",
            "callingCode": "1284",
            "countryCode": "VGB",
            "currencyCode": null,
            "currencyName": "[D]",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/vgb.svg",
            "isActive": true
        },
        {
            "id": 36,
            "country": "Virgin Islands (U.S.)",
            "callingCode": "1 340",
            "countryCode": "VIR",
            "currencyCode": "USD",
            "currencyName": "United States dollar",
            "curencySymbol": "$",
            "flag": "54.89.97.147:3002/static/data/vir.svg",
            "isActive": true
        },
        {
            "id": 246,
            "country": "Wallis and Futuna",
            "callingCode": "681",
            "countryCode": "WLF",
            "currencyCode": "XPF",
            "currencyName": "CFP franc",
            "curencySymbol": "Fr",
            "flag": "54.89.97.147:3002/static/data/wlf.svg",
            "isActive": true
        },
        {
            "id": 247,
            "country": "Western Sahara",
            "callingCode": "212",
            "countryCode": "ESH",
            "currencyCode": "MAD",
            "currencyName": "Moroccan dirham",
            "curencySymbol": "د.م.",
            "flag": "54.89.97.147:3002/static/data/esh.svg",
            "isActive": true
        },
        {
            "id": 248,
            "country": "Yemen",
            "callingCode": "967",
            "countryCode": "YEM",
            "currencyCode": "YER",
            "currencyName": "Yemeni rial",
            "curencySymbol": "﷼",
            "flag": "54.89.97.147:3002/static/data/yem.svg",
            "isActive": true
        },
        {
            "id": 249,
            "country": "Zambia",
            "callingCode": "260",
            "countryCode": "ZMB",
            "currencyCode": "ZMW",
            "currencyName": "Zambian kwacha",
            "curencySymbol": "ZK",
            "flag": "54.89.97.147:3002/static/data/zmb.svg",
            "isActive": true
        },
        {
            "id": 250,
            "country": "Zimbabwe",
            "callingCode": "263",
            "countryCode": "ZWE",
            "currencyCode": "BWP",
            "currencyName": "Botswana pula",
            "curencySymbol": "P",
            "flag": "54.89.97.147:3002/static/data/zwe.svg",
            "isActive": true
        },
        {
            "id": 2,
            "country": "Åland Islands",
            "callingCode": "358",
            "countryCode": "ALA",
            "currencyCode": "EUR",
            "currencyName": "Euro",
            "curencySymbol": "€",
            "flag": "54.89.97.147:3002/static/data/ala.svg",
            "isActive": true
        }
    ]